In [13]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'Setor':['abcd','defg'], 
                    'Grupo':['12345','67890'], 
                    'Pedido':['sim', 'nao']})
df

Setor  Grupo Pedido
0  abcd  12345    sim
1  defg  67890    nao

In [7]:
df.columns

Index(['Setor', 'Grupo', 'Pedido'], dtype='object')

In [5]:
df = pd.read_csv('teste.csv', sep=';')
df

Cd Consultora                         Nome CN    Nível  Ciclo Início  \
0           1985574                 IVONE ESPINDOLA  SEMENTE        202214   
1           2433710   NORY CELESTE SAIS DE FERREIRA  SEMENTE        202219   
2           2747120            MARIA JUANITA MORAES  SEMENTE        202218   
3           3234750              NILCE JUSTIN FERRI   BRONZE        202215   
4           3729010         DANIELA FABIANA PEREIRA   BRONZE        202217   
...             ...                             ...      ...           ...   
9385      307699820                  SHEILA DAMBROS  SEMENTE        202303   
9386      307760588                  CLAUDIA SANTOS  SEMENTE        202303   
9387      307764818       LEONARDO DE MATOS DA ROSA  SEMENTE        202303   
9388      307765733  JHONATAN SOARES OLIVEIRA SILVA  SEMENTE        202303   
9389      307768538    WESLEY RICARDO DOS REIS LIMA  SEMENTE        202303   

                   Setor  Grupo Débito Status CN Espaço Dig Aberto  \
0        ESTRELAS DO MAR  17259    NÃO        I1               SIM   
1       PAPAREIA DO CHUI   9037    NÃO        I4               SIM   
2              HORTENSIA   8611    NÃO        I3               SIM   
3        ESTRELAS DO MAR  17307    NÃO        I2               SIM   
4              HORTENSIA   8608    NÃO        I2               SIM   
...                  ...    ...    ...       ...               ...   
9385  TERRA DAS VIDEIRAS   8652    NÃO     ATIVA               SIM   
9386     PRINCESA DO SUL   9075    NÃO     ATIVA               SIM   
9387         BONS VENTOS  10194    NÃO     ATIVA               SIM   
9388          NOVO TEMPO   8201    NÃO     ATIVA               SIM   
9389  TERRA DAS VIDEIRAS   8656    NÃO     ATIVA               SIM   

     CN Bem Vinda Adimplente 1ª Parc Pedido Autônomo Treinamento  \
0             NÃO                SIM             SIM         NÃO   
1             NÃO                SIM             SIM         SIM   
2             NÃO                SIM             SIM         NÃO   
3             NÃO                SIM             SIM         NÃO   
4             NÃO                SIM             SIM         SIM   
...           ...                ...             ...         ...   
9385          NÃO                SIM             SIM         NÃO   
9386          NÃO                SIM             SIM         NÃO   
9387          NÃO                SIM             SIM         NÃO   
9388          NÃO                SIM             SIM         NÃO   
9389          NÃO                SIM             SIM         NÃO   

     Venda Digital  Qt Passos  
0              NÃO          2  
1              NÃO          3  
2              NÃO          2  
3              NÃO          2  
4              NÃO          3  
...            ...        ...  
9385           NÃO          2  
9386           NÃO          2  
9387           NÃO          2  
9388           NÃO          2  
9389           NÃO          2  

[9390 rows x 15 columns]

In [4]:
df[(df['Setor']=='CORAÇÃO GAÚCHO') & (df['Grupo']==9146) & (df['Nível']=='BRONZE')]['Cd Consultora'].count()

7

In [8]:
df[(df['Setor']=='CORAÇÃO GAÚCHO') & (df['Grupo']==9146)]['Cd Consultora'].count()

43

In [9]:
7/43

0.16279069767441862

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9390 entries, 0 to 9389
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Cd Consultora       9390 non-null   int64 
 1   Nome CN             9390 non-null   object
 2   Nível               9390 non-null   object
 3   Ciclo Início        9390 non-null   int64 
 4   Setor               9390 non-null   object
 5   Grupo               9390 non-null   int64 
 6   Débito              9390 non-null   object
 7   Status CN           9390 non-null   object
 8   Espaço Dig Aberto   9390 non-null   object
 9   CN Bem Vinda        9390 non-null   object
 10  Adimplente 1ª Parc  9390 non-null   object
 11  Pedido Autônomo     9390 non-null   object
 12  Treinamento         9390 non-null   object
 13  Venda Digital       9390 non-null   object
 14  Qt Passos           9390 non-null   int64 
dtypes: int64(4), object(11)
memory usage: 1.1+ MB


In [6]:
int('9146')

9146

In [3]:
df[df['Setor']=='CORAÇÃO GAÚCHO']['Grupo'].unique()

array([ 9146, 14573,  8989,  9148, 11167,  9144, 10163, 11277,  9087,
       12814])

Bad pipe message: %s [b'\xb4\x05\x9d\xe2_z\xb3\x1f\xcf\nj\x88p\xbe\xb5\xdf\xf0\x95 \xb8\xfdq\xbd\xc1\xfdo\x92~\x97\xdd\x15"\xa4#:FY\xfc\x81\x13R\x89c\xf4\xa1w\xeax\xcc\x7f\xa8\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08\n\x08\x0b\x08\x04\x08\x05\x08\x06', b'\x05\x01\x06', b'']
Bad pipe message: %s [b'\x03\x02\x03\x04\x00-\x00\x02\x01\x01\x003\x00&\x00$\x00\x1d\x00 c\xb6\xfc&\x01!\xfa\x0e\x0c\xa1&\xdd\x1d/\xc2\x99\xe4bd\xc8T\x08']
Bad pipe message: %s [b'+\xed\xdfDjl1nq\x0c6\xcb\xadq<@\x0c\x9e w\x92\xdd\xf0|\xd9@\xc4$\xfa\xb8\x199,\x8b+A\x05.\x0c\x14\x97\xde\x8d\x0c\xfdpq\x8a\xc0.i\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00

In [24]:
%%time
values = np.sort(df["Grupo"].unique())

CPU times: user 1.52 ms, sys: 90 µs, total: 1.61 ms
Wall time: 1.24 ms


In [25]:
values

array([    0,  8180,  8186,  8188,  8201,  8203,  8205,  8207,  8210,
        8212,  8215,  8219,  8220,  8223,  8232,  8233,  8237,  8242,
        8248,  8255,  8256,  8257,  8261,  8271,  8273,  8275,  8278,
        8279,  8284,  8286,  8287,  8296,  8593,  8595,  8597,  8598,
        8601,  8603,  8605,  8608,  8609,  8610,  8611,  8613,  8615,
        8616,  8618,  8622,  8633,  8634,  8636,  8639,  8640,  8643,
        8644,  8646,  8647,  8650,  8652,  8656,  8660,  8662,  8664,
        8665,  8667,  8669,  8671,  8673,  8675,  8677,  8679,  8683,
        8684,  8685,  8694,  8695,  8699,  8701,  8706,  8709,  8715,
        8716,  8717,  8719,  8726,  8728,  8989,  8996,  8997,  8998,
        8999,  9001,  9003,  9005,  9010,  9015,  9017,  9019,  9020,
        9025,  9028,  9030,  9032,  9035,  9037,  9039,  9043,  9045,
        9046,  9049,  9051,  9052,  9054,  9056,  9060,  9063,  9066,
        9071,  9072,  9075,  9076,  9080,  9081,  9082,  9087,  9095,
        9097,  9099,

In [26]:
values[values > 0]

array([ 8180,  8186,  8188,  8201,  8203,  8205,  8207,  8210,  8212,
        8215,  8219,  8220,  8223,  8232,  8233,  8237,  8242,  8248,
        8255,  8256,  8257,  8261,  8271,  8273,  8275,  8278,  8279,
        8284,  8286,  8287,  8296,  8593,  8595,  8597,  8598,  8601,
        8603,  8605,  8608,  8609,  8610,  8611,  8613,  8615,  8616,
        8618,  8622,  8633,  8634,  8636,  8639,  8640,  8643,  8644,
        8646,  8647,  8650,  8652,  8656,  8660,  8662,  8664,  8665,
        8667,  8669,  8671,  8673,  8675,  8677,  8679,  8683,  8684,
        8685,  8694,  8695,  8699,  8701,  8706,  8709,  8715,  8716,
        8717,  8719,  8726,  8728,  8989,  8996,  8997,  8998,  8999,
        9001,  9003,  9005,  9010,  9015,  9017,  9019,  9020,  9025,
        9028,  9030,  9032,  9035,  9037,  9039,  9043,  9045,  9046,
        9049,  9051,  9052,  9054,  9056,  9060,  9063,  9066,  9071,
        9072,  9075,  9076,  9080,  9081,  9082,  9087,  9095,  9097,
        9099,  9111,

In [21]:
filter_values = values > 0

In [22]:
filter_values

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [23]:
new_values = values[filter_values]
new_values

array([ 8180,  8186,  8188,  8201,  8203,  8205,  8207,  8210,  8212,
        8215,  8219,  8220,  8223,  8232,  8233,  8237,  8242,  8248,
        8255,  8256,  8257,  8261,  8271,  8273,  8275,  8278,  8279,
        8284,  8286,  8287,  8296,  8593,  8595,  8597,  8598,  8601,
        8603,  8605,  8608,  8609,  8610,  8611,  8613,  8615,  8616,
        8618,  8622,  8633,  8634,  8636,  8639,  8640,  8643,  8644,
        8646,  8647,  8650,  8652,  8656,  8660,  8662,  8664,  8665,
        8667,  8669,  8671,  8673,  8675,  8677,  8679,  8683,  8684,
        8685,  8694,  8695,  8699,  8701,  8706,  8709,  8715,  8716,
        8717,  8719,  8726,  8728,  8989,  8996,  8997,  8998,  8999,
        9001,  9003,  9005,  9010,  9015,  9017,  9019,  9020,  9025,
        9028,  9030,  9032,  9035,  9037,  9039,  9043,  9045,  9046,
        9049,  9051,  9052,  9054,  9056,  9060,  9063,  9066,  9071,
        9072,  9075,  9076,  9080,  9081,  9082,  9087,  9095,  9097,
        9099,  9111,

In [17]:
%%time
df["Grupo"].sort_values().unique()

CPU times: user 2.31 ms, sys: 173 µs, total: 2.48 ms
Wall time: 2.39 ms


array([    0,  8180,  8186,  8188,  8201,  8203,  8205,  8207,  8210,
        8212,  8215,  8219,  8220,  8223,  8232,  8233,  8237,  8242,
        8248,  8255,  8256,  8257,  8261,  8271,  8273,  8275,  8278,
        8279,  8284,  8286,  8287,  8296,  8593,  8595,  8597,  8598,
        8601,  8603,  8605,  8608,  8609,  8610,  8611,  8613,  8615,
        8616,  8618,  8622,  8633,  8634,  8636,  8639,  8640,  8643,
        8644,  8646,  8647,  8650,  8652,  8656,  8660,  8662,  8664,
        8665,  8667,  8669,  8671,  8673,  8675,  8677,  8679,  8683,
        8684,  8685,  8694,  8695,  8699,  8701,  8706,  8709,  8715,
        8716,  8717,  8719,  8726,  8728,  8989,  8996,  8997,  8998,
        8999,  9001,  9003,  9005,  9010,  9015,  9017,  9019,  9020,
        9025,  9028,  9030,  9032,  9035,  9037,  9039,  9043,  9045,
        9046,  9049,  9051,  9052,  9054,  9056,  9060,  9063,  9066,
        9071,  9072,  9075,  9076,  9080,  9081,  9082,  9087,  9095,
        9097,  9099,